---
title: "nCounter_RNA_Analysis"
author: "Ned Cauley"
date: "12/13/23"
output: html_document
---

# This markdown and analysis based on https://github.com/bhattacharya-a-bt/CBCS_normalization/blob/master/sabry_analysis.R
# The above analysis is from the publication https://academic.oup.com/bib/article/22/3/bbaa163/5891144?login=true

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
```

## Set up libraries and QC functions libraries

```{r Libraries and RUVseq functions, message=FALSE, warning=FALSE}
library(NanoStringQCPro)
library(ggplot2)
library(EnvStats)
library(MASS)
library(RUVSeq)
library(DESeq2)
library(limma)
library(matrixStats)
library(limma)
library(NanoStringNorm)
library(readxl)
library(plotly)
library(pheatmap)

# The library in RSW to use is located at
# /home/cauleyes/ccbr-data/renv_cache/ncounter_rna/Snapshot-environment_method/renv/library/R-4.1/x86_64-pc-linux-gnu

# Set the working directory to your project folder if it is not set already
setwd("/home/cauleyes/ccbr-data/users/Ned/nCounter_rna/CCBR1245_Ramaswami_nCounter")

# Functions for RUVseq analysis
source("R/nanostring_RUV_functions.R")

# Load the annotation file
annotation_file_path <- "ncounter_rna_annotation_edit_correction_RR.xlsx"
annotation_df <- read_excel(annotation_file_path)

```

```{r Define the contrast for the DEG analysis, message=FALSE, warning=FALSE}

# Define the contrast and levels from the annotation columns for QC and DEG analysis
contrast <- "CD4_group"
#contrast <- "KS_alone"
#contrast <- "KSHV_VL_Bin"

# Levels are: Reference, Effect. 
# This means a positive log2foldchnage = lower reference, higher effect
contrast_levels <- c("High", "Low")
#contrast_levels <- c("Y", "N")
#contrast_levels <- c("0", "1")

```


## Setup the initial dataframes with read counts and metadata/QC

```{r Initial Dataframes and QC,  message=FALSE, warning=FALSE}
# Gather the names of the RCC files
files.RCC = list.files("/rstudio-files/ccbr-data/users/Ned/nCounter_rna/data/CCBR1245/rcc")
files.RCC = files.RCC[grepl('RCC',files.RCC)]
# Add name of sub folder containing RCC files
rcc_folder <- "/rstudio-files/ccbr-data/users/Ned/nCounter_rna/data/CCBR1245/rcc"
#files.RCC <- file.path(rcc_folder, files.RCC)

# Gather number of genes and samples
rcc.example.file <- file.path(rcc_folder, files.RCC[1])
#genes.count = nrow(readRcc(file.path(rcc_folder, files.RCC[1])$Code_Summary))
genes.count = nrow(readRcc(rcc.example.file)$Code_Summary)
ncol = length(files.RCC)

# Set up the dataframe to hold all sample and gene data
raw_expression = as.data.frame(matrix(nrow = genes.count,ncol = length(files.RCC)+2))
colnames(raw_expression)[1:2] = c('Gene','Class')

# Set up a dataframe to hold metadata and QC
pData = as.data.frame(matrix(nrow = length(files.RCC),ncol = 11))
colnames(pData) = c('BCAC_ID','SampleID','Owner','Comments','Date','GeneRLF','SystemAPF','imagingQC',
                    'bindingDensityQC','limitOfDetectionQC','positiveLinearityQC')

# Populate gene and class columns of expression df
raw_expression[,1:2] = readRcc(rcc.example.file)$Code_Summary[,c(2,1)]

print("RCC files to be processed:")
# Populate expression df, run QC, and record flags for each sample
for (i in 1:length(files.RCC)){
  
  print(files.RCC[i])
  rcc.path <- file.path(rcc_folder, files.RCC[i])
  rcc = readRcc(rcc.path)
  raw = rcc$Code_Summary
  
  raw_expression[,i+2] = as.numeric(raw$Count)
  colnames(raw_expression)[i+2] = strsplit(files.RCC[i],'_')[[1]][3]
  pData[i,2:7] = as.vector(rcc$Sample_Attributes)
  pData$imagingQC[i] = imagingQC(rcc)
  pData$imaging[i] <-  as.numeric(rcc$Lane_Attributes[3])
  pData$bindingDensityQC[i] = bindingDensityQC(rcc,.05,2.25)
  pData$bindingDensity[i] <- as.numeric(rcc$Lane_Attributes[6])
  pData$limitOfDetectionQC[i] = limitOfDetectionQC(rcc)
  pData$limitOfDetection[i] <- limitOfDetectionScore(rcc)
  pData$positiveLinearityQC[i] = positiveLinQC(rcc)
  pData$positiveLinearityQC[i] <- positiveLinScore(rcc)
}

# Correct the sample ID column name and sample name IDs
# Correct for annotation
colnames(annotation_df)[4] <- "SampleID"
annotation_df$"SampleID" <- gsub("-", " ", annotation_df$"SampleID")
annotation_df$"SampleID" <- gsub("\\sSB", "SB", annotation_df$"SampleID")

# Correct for pdata
pData$"SampleID" <- gsub("-", " ", pData$"SampleID")
pData$"SampleID" <- gsub("\\sSB", "SB", pData$"SampleID")

# Rename and factor the KS alone field and sort by Yes or No
colnames(annotation_df)[colnames(annotation_df) == "KS alone"] <- "KS_alone"
colnames(annotation_df)[colnames(annotation_df) == "CD4 count...11"] <- "CD4_group"
colnames(annotation_df)[colnames(annotation_df) == "KSHV VL Bin"] <- "KSHV_VL_Bin"

# Combine all metadata into a single dataframe
merged_pData <- merge(pData, annotation_df, by = "SampleID")

merged_pData[[contrast]] <- factor(merged_pData[[contrast]], levels = contrast_levels)

# Create a feature df
raw = raw_expression[,-c(1:2)]
fData = raw_expression[,c(1:2)]
rownames(raw) = fData$Gene

# Correct the Sample ID column names for preceding spaces and hyphens
colnames(raw) <- gsub("^\\s+", "", colnames(raw))
colnames(raw) <- gsub("-", " ", colnames(raw))


# List the information for the feature data frame
str(fData)
count_endog <- sum(fData$Class == "Endogenous")
count_neg <- sum(fData$Class == "Negative")
count_pos <- sum(fData$Class == "Positive")
count_hk <- sum(fData$Class == "Housekeeping")

print(paste0("Endogenous genes: ",count_endog))
print(paste0("Negative genes: ",count_neg))
print(paste0("Positive genes: ",count_pos))
print(paste0("Housekeeping geness: ",count_hk))

# List the housekeeping genes and label in the fData df
cIdx <- fData$Gene[fData$Class == "Housekeeping"]

# Identify missing housekeeping genes in any samples
merged_pData$HK_Gene_Miss = colSums(raw[cIdx,] == 0)

# Estbalish all of the rownames of the three dfs
rownames(fData) = fData$Gene
rownames(raw) = fData$Gene
rownames(merged_pData) <- merged_pData$SampleID

# Ensure the order of the SampleID columns in the expression data frame match the order of the rows in the metadata
raw_reorder <- raw[, rownames(merged_pData)]

# Remove outlier sample
remove_outlier <- FALSE
if(remove_outlier == TRUE){
  
  outlier <- "SB 19 5920"
  
  # Remove from annotation
  merged_pData <- merged_pData[merged_pData$SampleID != outlier, ]
  
  # Remove from counts
  raw_reorder <- raw_reorder[, !names(raw_reorder) %in% outlier]
}

print("Initial data frames")
head(raw_reorder)
head(merged_pData)
head(fData)

```

## Verify that housekeeping genes are not DEGs

```{r, message=FALSE, warning=FALSE}
###
#### CHECK IF HK ARE ASSOCIATED WITH PRIMARY PHENO
###

# Gather the read counts for housekeeping genes
hk_raw = raw_reorder[cIdx,]
pval = vector(length = nrow(hk_raw))

# Run general linear model to get pvalue for housekeeping
for (i in 1:nrow(hk_raw)){
  
  reg = glm.nb(as.numeric(hk_raw[i,]) ~ as.factor(merged_pData[[contrast]]))
  pval[i] = coef(summary(reg))[2,4]
  
}

print("Housekeeping genes:")
print(rownames(hk_raw))

# Number of housekeeping that are DE
print("Number of housekeeping genes that are DE:")
sum(pval <= .05)

```

## Run RUVseq differential expression analysis

```{r, message=FALSE, warning=FALSE}


# Number of sources of variance to identify with RUVseq
k = 1

# Remove samples with NA from the read counts dataframe
NA_rows <- which(!complete.cases(merged_pData[[contrast]]))
NA_samples <- rownames(merged_pData[NA_rows, ])

if(length(NA_rows) > 0){
  raw_reorder <- raw_reorder[, -which(names(raw_reorder) %in% NA_samples)]
}



# Remove sample with NA from the annotation
if(length(NA_rows) > 0){
  merged_pData <- merged_pData[complete.cases(merged_pData[[contrast]]), ]
}



# DEseq transform for RUVseq
vsd = RUV_total(raw_reorder,merged_pData,fData,k = k)$vsd
# Set Expression Set
set = RUV_total(raw_reorder,merged_pData,fData,k = k)$set

# Remove row of the contrast that contain NA values
set <- set[complete.cases(pData(set)$KSHV_VL_Bin), ]

# Save the results
save(vsd,file = paste0("cauley_ruv_vsd_k_",k,".rda"))
save(set,file = paste0("cauley_ruv_set_k_",k,".rda"))


i = 1

results = paste0("cauley_deg_k",i,".csv")
load(paste0("cauley_ruv_set_k_",i,".rda"))
# DEseq Dataset

# Should date of the experiment be used as a covariate?
date_covariate <- TRUE

if(date_covariate == FALSE){
  dds <- DESeqDataSetFromMatrix(countData = counts(set)[1:nrow(set),],
                              colData = pData(set),
                              design = as.formula(paste("~ W_1 + Date + ", contrast)))
} else{
  dds <- DESeqDataSetFromMatrix(countData = counts(set)[1:nrow(set),],
                              colData = pData(set),
                              design = as.formula(paste("~ W_1 + ", contrast)))
}



# Run DEseq
dds <- DESeq(dds)

# Generate contrasts per group
contrast_ruv <- as.data.frame(results(dds,contrast = c(contrast, contrast_levels)))

contrast_ruv_deg_list <- contrast_ruv[contrast_ruv$pvalue < 0.05, ]

# Reformat the DEG table to be exported
ruv_deg_list_export <- contrast_ruv_deg_list
ruv_deg_list_export$gene <- rownames(ruv_deg_list_export)
rownames(ruv_deg_list_export) <- NULL
ruv_deg_list_export <- ruv_deg_list_export[, c("gene", setdiff(names(ruv_deg_list_export), "gene"))]
ruv_deg_list_export$normalization <- "RUVseq"


# Export Normalized read counts
export_norm_counts <- TRUE
if(export_norm_counts == TRUE){
  # Grab the normalized_counts
  normalized_counts <- as.data.frame(counts(dds, normalized = TRUE))
  
  # Add a gene column
  gene <- rownames(normalized_counts)
  normalized_counts <- cbind(gene, normalized_counts) 
  
  # Export
  write.csv(normalized_counts, file = paste0("Results/RUV_normalized_counts.csv"), row.names = FALSE)
  
  
}

# Plot PCA to check for batch effects

# Prepare the counts
rlog_dds <- rlog(dds)

# Annotation to view PCA by
PCA.group <- "Date"

# PCA Plot
PCA.plot <- plotPCA(rlog_dds, intgroup = PCA.group, ntop = 700)

# Plotly PCA for interactivity
PCA.plot.data <- plotPCA(rlog_dds, intgroup = PCA.group, ntop = 700, returnData = TRUE)
PCA.plotly <- plot_ly(data = PCA.plot.data, x = ~PC1, y = ~PC2, text = ~name, mode = "markers", color = ~factor(group)) %>%
  layout(title = "PCA Plot",
         xaxis = list(title = "PC1"),
         yaxis = list(title = "PC2"))

print(PCA.plotly)

# Export the PCA plot

export.PCA <- TRUE
if(export.PCA == TRUE){
  ggsave(paste0("Results/QC/PCA.pdf"), plot = PCA.plot)
}

```
# Get the read count information for CXCL8

```{r}

normalized_CXCL8 <- set@assayData$counts[rownames(set@assayData$counts) == "CXCL8", ]


CXCL8_df <- data.frame(CXCL8_normalized = normalized_CXCL8, SampleID = names(normalized_CXCL8))
rownames(CXCL8_df) = NULL

CXCL8_anno_columns <- c("SampleID","KS_alone","CD4_group")
subset_anno_df <- annotation_df[CXCL8_anno_columns]


CXCL8_df <- merge(CXCL8_df, subset_anno_df, by = "SampleID")

CXCL8_mean_KS_Y <- mean(CXCL8_df$CXCL8_normalized[CXCL8_df$KS_alone == "Y"], na.rm = TRUE)
CXCL8_mean_KS_N <- mean(CXCL8_df$CXCL8_normalized[CXCL8_df$KS_alone == "N"], na.rm = TRUE)

CXCL8_df$KS_alone_mean <- ifelse(CXCL8_df$KS_alone == "Y", CXCL8_mean_KS_Y, CXCL8_mean_KS_N)

CXCL8_mean_CD4_High <- mean(CXCL8_df$CXCL8_normalized[CXCL8_df$CD4_group == "High"], na.rm = TRUE)
CXCL8_mean_CD4_Low <- mean(CXCL8_df$CXCL8_normalized[CXCL8_df$CD4_group == "Low"], na.rm = TRUE)

CXCL8_df$CD4_group_mean <- ifelse(CXCL8_df$CD4_group == "High", CXCL8_mean_CD4_High, CXCL8_mean_CD4_Low)



CXCL8_deg <- ruv_deg_list_export[ruv_deg_list_export$gene == "CXCL8", ]

export_CXCL8_summary <- TRUE
if(export_CXCL8_summary == TRUE){
  write.csv(CXCL8_df, file = "Results/CXCL8_summary.csv", row.names = FALSE)
}


```

# Heatmap of Variable Genes

```{r}

# Prepare the normalized counts
log.norm.counts <- log2(counts(dds, normalized = TRUE) + 1)

# Prepare the annotation columns
anno.columns <- c("KS_alone", "CD4_group")
annotation_df <- as.data.frame(annotation_df)

# Ensure the row names are the sample names
rownames(annotation_df) <- annotation_df$SampleID
heatmap.annotation <- annotation_df[ ,anno.columns]

# Order the annotation
heatmap.annotation <- heatmap.annotation %>% 
  arrange(CD4_group) %>% arrange(KS_alone)

# Define the colors for the annotations
anno.colors = list(
  KS_alone = c(Y = "seagreen", N = "red4"), 
  CD4_group = c(High = "purple", Low = "coral")
  )

# Determine the most variable genes using the coefficient of variation
.calcCv <- function(x) {
  sd(x) / mean(x)
}
cv.vector <- apply(log.norm.counts, 1, .calcCv)

# Identify the NEG and POS probes
NEG.indices <- grep("NEG_", names(cv.vector))
POS.indices <- grep("POS_", names(cv.vector))
control.indices <- c(NEG.indices, POS.indices)

# Print the names of the control probes to be removed
control.probes <- names(cv.vector)[control.indices]
print(control.probes)

# Remove the control probes
cv.vector <- cv.vector[-control.indices]

# Sort the genes based on variability
cv.vector <- sort(cv.vector, decreasing = TRUE)

# Top variable genes
ngenes <- 50
goi <- names(cv.vector)[1:ngenes]

# Reorder the data columns to they match the annotation row order
row.order <- rownames(heatmap.annotation)
log.norm.counts <- log.norm.counts[, row.order]


# Top 50 genes
heatmap.top50 <- pheatmap(log.norm.counts[goi, ], 
         main = "Top 50 Variable Genes", 
         show_rownames = TRUE, 
         scale = "row", 
         show_colnames = TRUE,
         border_color = NA, 
         cluster_rows = TRUE, 
         cluster_cols = FALSE, 
         clustering_method = "average", 
         clustering_distance_rows = "correlation", 
         clustering_distance_cols = "correlation", 
         color = colorRampPalette(c("blue", "white", "red"))(120), 
         annotation_row = NA, 
         annotation_col = heatmap.annotation, 
         annotation_colors = anno.colors
         )

export.top50 <- FALSE
if(export.top50 == TRUE){
  
  ggsave("Results/heatmap_top50.png",
         plot = heatmap.top50, 
         width = 10, 
         height = 10, 
         units = "in")
  
}

# Create a heatmap with all genes
heatmap.all <- pheatmap(log.norm.counts, 
         main = "All Genes", 
         show_rownames = FALSE, 
         scale = "row", 
         show_colnames = TRUE,
         border_color = NA, 
         cluster_rows = TRUE, 
         cluster_cols = FALSE, 
         clustering_method = "average", 
         clustering_distance_rows = "correlation", 
         clustering_distance_cols = "correlation", 
         color = colorRampPalette(c("blue", "white", "red"))(120), 
         annotation_row = NA, 
         annotation_col = heatmap.annotation, 
         annotation_colors = anno.colors
         )

export.heatmap.all <- FALSE
if(export.heatmap.all == TRUE){
  
  ggsave("Results/heatmap_all.png",
         plot = heatmap.all, 
         width = 10, 
         height = 10, 
         units = "in")
  
}


# Create a heatmap for the DEGs from the DEG contrast

# Get a list of the DEGS
contrast_deg_list <- rownames(contrast_ruv[contrast_ruv$padj < 0.10, ])

# Remove the positive and negative probes
# Identify the NEG and POS probes
NEG.indices <- grep("NEG_", contrast_deg_list)
POS.indices <- grep("POS_", contrast_deg_list)
control.indices <- c(NEG.indices, POS.indices)

# Remove the control probes
if(length(control.indices) > 0){
  goi <- contrast_deg_list[-control.indices]
} else{
  goi <- contrast_deg_list
}


# Gather the annotation for the contrast
anno.columns <- c(contrast)
annotation_df <- as.data.frame(annotation_df)

# Ensure the row names are the sample names
rownames(annotation_df) <- annotation_df$SampleID
heatmap.annotation <- annotation_df[ ,anno.columns, drop = FALSE]

# Order the annotation
heatmap.annotation <- heatmap.annotation %>% arrange(.data[[contrast]])

# Reorder the data columns to they match the annotation row order
row.order <- rownames(heatmap.annotation)
log.norm.counts <- log.norm.counts[, row.order]

# Define the annotation colors for the contrast
anno.colors1 = list(
  KS_alone = c(Y = "seagreen", N = "red4")
  )

anno.colors2 = list(
  CD4_group = c(High = "purple", Low = "coral")
  )

heatmap.contrast <- pheatmap(log.norm.counts[goi, ], 
         main = paste0("DEGs for ", contrast), 
         show_rownames = TRUE, 
         scale = "row", 
         show_colnames = TRUE,
         border_color = NA, 
         cluster_rows = TRUE, 
         cluster_cols = FALSE, 
         clustering_method = "average", 
         clustering_distance_rows = "correlation", 
         clustering_distance_cols = "correlation", 
         color = colorRampPalette(c("blue", "white", "red"))(120), 
         annotation_row = NA, 
         annotation_col = heatmap.annotation, 
         annotation_colors = anno.colors2
         )


export.heatmap.contrast <- TRUE
if(export.heatmap.contrast == TRUE){
  
  ggsave(paste0("Results/heatmap_", contrast, ".png"),
         plot = heatmap.contrast, 
         width = 10, 
         height = 10, 
         units = "in")
  
}

print(heatmap.top50)
print(heatmap.all)
print(heatmap.contrast)



```
